# Workflow name
name: CI

# Controls when the action will run
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checkout the repository
    - name: Checkout the repository
      uses: actions/checkout@v2

    # Install dependencies
    - name: Install dependencies -> Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14

    # # Search for secrets
    # - name: Search for secrets -> Trufflehog
    #   uses: edplato/trufflehog-actions-scan@v0.9i-beta

    # # Lint Dockerfile
    # - name: Lint Dockerfile -> Hadolint
    #   uses: brpaz/hadolint-action@v1.1.0

    # Build docker image
    - name: Build docker image
      run: docker build -t docker.io/nahueloyha/tp-sr:${{ github.sha }} .

    # # Scan for vulnerabilities -> SonarCloud
    # - name: Scan for vulnerabilities -> SonarCloud
    #   uses: SonarSource/sonarcloud-github-action@v1.3
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    # Scan for vulnerabilities -> Trivy
    - name: Scan for vulnerabilities -> Trivy
      uses: aquasecurity/trivy-action@0.0.7
      with:
        image-ref: 'docker.io/nahueloyha/tp-sr:${{ github.sha }}'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'HIGH,CRITICAL'

    # # Runs a single command using the runners shell
    # - name: Run a one-line script
    #   run: echo Hello, world!
